name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          mkdir .out
          cp ./public/*.js .out
          cd .out
          echo "<html><body style='font-size: xx-large;'><h1><b>Scripts listing</b></h1>" > index.html
          find -exec echo "<a href='{}'>{}</a><br/>" \; >> index.html
          echo "</body></html>" >> index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .out
